---
all:
  children:
    vpn_servers:
      hosts:
        vpn-server-1:
          ansible_host: 
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/vpn-cluster-new-key.pem"
  vars:
    ansible_python_interpreter: /usr/bin/python3
