---
all:
  children:
    vpn_servers:
      hosts:
        vpn-server-1:
          ansible_host: 13.230.134.45
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/vpn-cluster-new-key.pem"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    nlb_endpoint: "vpn-cluster-vpn-dev-f47985dfbf25d8d1.elb.ap-northeast-1.amazonaws.com"
